#!/bin/bash
# ─────────────────────────────────────────────────────────────────
#  osTicket Entrypoint — Zero-touch automated installer
#  Runs on every container start; idempotent (safe to re-run)
# ─────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Colours for readable logs ─────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; NC='\033[0m'

log()  { echo -e "${CYAN}[$(date '+%H:%M:%S')]${NC} $*"; }
ok()   { echo -e "${GREEN}[$(date '+%H:%M:%S')] ✓${NC} $*"; }
warn() { echo -e "${YELLOW}[$(date '+%H:%M:%S')] ⚠${NC} $*"; }
err()  { echo -e "${RED}[$(date '+%H:%M:%S')] ✗${NC} $*"; }

# ── Required env vars (with defaults from compose) ────────────────
MYSQL_HOST="${MYSQL_HOST:-mysql}"
MYSQL_PORT="${MYSQL_PORT:-3306}"
MYSQL_DATABASE="${MYSQL_DATABASE:-osticket}"
MYSQL_USER="${MYSQL_USER:-osticket}"
MYSQL_PASSWORD="${MYSQL_PASSWORD:-0sT1ck3tPass!}"
MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD:-R00tS3cur3Pass!}"
MYSQL_PREFIX="${MYSQL_PREFIX:-ost_}"

OST_ADMIN_EMAIL="${OST_ADMIN_EMAIL:-admin@example.com}"
OST_ADMIN_FNAME="${OST_ADMIN_FNAME:-Admin}"
OST_ADMIN_LNAME="${OST_ADMIN_LNAME:-User}"
OST_ADMIN_USER="${OST_ADMIN_USER:-ostadmin}"
OST_ADMIN_PASS="${OST_ADMIN_PASS:-Adm1nP@ss!}"

OST_SITE_NAME="${OST_SITE_NAME:-Support Center}"
OST_SITE_EMAIL="${OST_SITE_EMAIL:-support@example.com}"
OST_HELPDESK_URL="${OST_HELPDESK_URL:-http://localhost:8080}"

INSTALL_FLAG="/var/www/html/attachments/.installed"
CONFIG_FILE="/var/www/html/include/ost-config.php"
WEB_ROOT="/var/www/html"

# ─────────────────────────────────────────────────────────────────
#  1. WAIT FOR MYSQL
# ─────────────────────────────────────────────────────────────────
wait_for_mysql() {
    log "Waiting for MySQL at ${MYSQL_HOST}:${MYSQL_PORT}..."
    local retries=0
    local max=60

    # Phase 1: wait for TCP port to be open (works regardless of auth)
    until nc -z "${MYSQL_HOST}" "${MYSQL_PORT}" 2>/dev/null; do
        retries=$((retries + 1))
        if [ $retries -ge $max ]; then
            err "MySQL TCP port never opened. Aborting."
            err "DNS check: $(getent hosts ${MYSQL_HOST} 2>&1 || echo 'hostname not resolved')"
            err "Network: $(ip route 2>/dev/null | head -5)"
            exit 1
        fi
        # Every 10 attempts, print a status line
        if [ $((retries % 10)) -eq 0 ]; then
            echo ""
            log "Still waiting... attempt ${retries}/${max}. DNS: $(getent hosts ${MYSQL_HOST} 2>/dev/null || echo 'unresolved')"
        else
            echo -n "."
        fi
        sleep 2
    done
    echo ""
    log "MySQL TCP port is open. Waiting for server to accept queries..."

    # Phase 2: wait for MySQL to actually accept connections
    # Use root for the ping — the osticket user may not exist yet
    retries=0
    until mysqladmin ping \
          -h"${MYSQL_HOST}" \
          -P"${MYSQL_PORT}" \
          -uroot \
          -p"${MYSQL_ROOT_PASSWORD}" \
          --ssl=0 \
          --silent 2>/dev/null; do
        retries=$((retries + 1))
        if [ $retries -ge $max ]; then
            err "MySQL did not become ready in time. Aborting."
            exit 1
        fi
        echo -n "."
        sleep 2
    done
    echo ""
    ok "MySQL is ready."
}

# ─────────────────────────────────────────────────────────────────
#  2. WRITE ost-config.php
# ─────────────────────────────────────────────────────────────────
write_config() {
    log "Writing ost-config.php..."
    chmod 0666 "${CONFIG_FILE}"

    # Build the config — we patch the sample config in-place
    # osTicket's config format uses define() calls
    cat > "${CONFIG_FILE}" << PHPCONFIG
<?php
# osTicket Configuration — auto-generated by Docker entrypoint
# DO NOT EDIT MANUALLY

define('OSTINSTALLED',TRUE);
define('SECRET_SALT','$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)');
define('DBDRIVER','mysqli');
define('DBHOST','${MYSQL_HOST}');
define('DBNAME','${MYSQL_DATABASE}');
define('DBUSER','${MYSQL_USER}');
define('DBPASS','${MYSQL_PASSWORD}');
define('DBPREFIX','${MYSQL_PREFIX}');
define('DBPORT','${MYSQL_PORT}');
define('DBSSLCA','');
define('DBSSLCERT','');
define('DBSSLKEY','');
define('DBSSL',false);

define('TABLE_PREFIX','${MYSQL_PREFIX}');

@define('ATTACHMENT_PATH','${WEB_ROOT}/attachments/');
@define('BOOTSTRAP','${WEB_ROOT}/bootstrap.php');
PHPCONFIG

    # Lock config after writing
    chmod 0644 "${CONFIG_FILE}"
    chown www-data:www-data "${CONFIG_FILE}"
    ok "ost-config.php written."
}

# ─────────────────────────────────────────────────────────────────
#  3. RUN CLI INSTALLER
# ─────────────────────────────────────────────────────────────────
run_installer() {
    log "Running osTicket CLI installer..."

    # osTicket's CLI installer: setup/cli/manage.php install
    /usr/local/bin/php "${WEB_ROOT}/setup/cli/manage.php" install \
        --dbhost="${MYSQL_HOST}" \
        --dbport="${MYSQL_PORT}" \
        --dbname="${MYSQL_DATABASE}" \
        --dbuser="${MYSQL_USER}" \
        --dbpass="${MYSQL_PASSWORD}" \
        --prefix="${MYSQL_PREFIX}" \
        --sname="${OST_SITE_NAME}" \
        --semail="${OST_SITE_EMAIL}" \
        --fname="${OST_ADMIN_FNAME}" \
        --lname="${OST_ADMIN_LNAME}" \
        --admin-email="${OST_ADMIN_EMAIL}" \
        --admin-user="${OST_ADMIN_USER}" \
        --admin-passwd="${OST_ADMIN_PASS}"

    local exit_code=$?
    if [ $exit_code -ne 0 ]; then
        err "CLI installer failed (exit code: $exit_code)."
        err "Attempting fallback SQL-based install..."
        sql_fallback_install
        return
    fi

    ok "CLI installer completed successfully."
}

# ─────────────────────────────────────────────────────────────────
#  4. FALLBACK: Direct SQL install (in case CLI installer fails)
# ─────────────────────────────────────────────────────────────────
sql_fallback_install() {
    log "Running SQL fallback installer..."

    local sql_file="${WEB_ROOT}/setup/inc/streams/core/install-mysql.sql"
    if [ ! -f "${sql_file}" ]; then
        err "Install SQL file not found at: ${sql_file}"
        exit 1
    fi

    # Replace table prefix placeholder in SQL
    local tmp_sql="/tmp/osticket-install-$(date +%s).sql"
    sed "s/ost_/${MYSQL_PREFIX}/g" "${sql_file}" > "${tmp_sql}"

    # Run the schema SQL
    mysql -h"${MYSQL_HOST}" -P"${MYSQL_PORT}" \
          --ssl=0 \
          -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" \
          "${MYSQL_DATABASE}" < "${tmp_sql}"

    rm -f "${tmp_sql}"

    # Insert admin account and site settings via PHP helper
    php -r "
    define('OSTINSTALLED', TRUE);
    define('DBHOST', '${MYSQL_HOST}');
    define('DBPORT', '${MYSQL_PORT}');
    define('DBNAME', '${MYSQL_DATABASE}');
    define('DBUSER', '${MYSQL_USER}');
    define('DBPASS', '${MYSQL_PASSWORD}');
    define('TABLE_PREFIX', '${MYSQL_PREFIX}');
    define('DBPREFIX', '${MYSQL_PREFIX}');
    define('SECRET_SALT', '$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)');
    define('BOOTSTRAP', '${WEB_ROOT}/bootstrap.php');

    \$conn = new mysqli('${MYSQL_HOST}', '${MYSQL_USER}', '${MYSQL_PASSWORD}', '${MYSQL_DATABASE}', ${MYSQL_PORT});
    if (\$conn->connect_error) { die('DB connect failed: ' . \$conn->connect_error . PHP_EOL); }

    // Insert default config
    \$site_name   = \$conn->real_escape_string('${OST_SITE_NAME}');
    \$site_email  = \$conn->real_escape_string('${OST_SITE_EMAIL}');
    \$helpdesk_url = \$conn->real_escape_string('${OST_HELPDESK_URL}');

    \$conn->query(\"UPDATE ${MYSQL_PREFIX}config SET value='\$site_name'  WHERE namespace='core' AND key_name='helpdesk_title'\");
    \$conn->query(\"UPDATE ${MYSQL_PREFIX}config SET value='\$site_email' WHERE namespace='core' AND key_name='default_email'\");
    \$conn->query(\"UPDATE ${MYSQL_PREFIX}config SET value='\$helpdesk_url' WHERE namespace='core' AND key_name='helpdesk_url'\");

    // Hash admin password (osTicket uses md5-based hash — matches their Auth class)
    \$salt   = substr(md5(uniqid(rand(), true)), -16);
    \$passwd = md5(\$salt . '${OST_ADMIN_PASS}' . \$salt);

    \$fname  = \$conn->real_escape_string('${OST_ADMIN_FNAME}');
    \$lname  = \$conn->real_escape_string('${OST_ADMIN_LNAME}');
    \$email  = \$conn->real_escape_string('${OST_ADMIN_EMAIL}');
    \$uname  = \$conn->real_escape_string('${OST_ADMIN_USER}');

    // Check if staff table already has a record
    \$res = \$conn->query(\"SELECT COUNT(*) as cnt FROM ${MYSQL_PREFIX}staff\");
    \$row = \$res->fetch_assoc();
    if (\$row['cnt'] == 0) {
        \$now = date('Y-m-d H:i:s');
        \$conn->query(\"INSERT INTO ${MYSQL_PREFIX}staff
            (firstname, lastname, email, username, passwd, isadmin, isactive, created, updated)
            VALUES ('\$fname', '\$lname', '\$email', '\$uname', '\$passwd::\$salt', 1, 1, '\$now', '\$now')\");
        echo 'Admin account created.' . PHP_EOL;
    } else {
        echo 'Admin account already exists, skipping.' . PHP_EOL;
    }

    \$conn->close();
    echo 'SQL fallback install complete.' . PHP_EOL;
    "

    ok "SQL fallback install done."
}

# ─────────────────────────────────────────────────────────────────
#  5. POST-INSTALL CLEANUP
# ─────────────────────────────────────────────────────────────────
post_install_cleanup() {
    log "Running post-install cleanup..."

    # Remove setup directory (security requirement)
    if [ -d "${WEB_ROOT}/setup" ]; then
        rm -rf "${WEB_ROOT}/setup"
        ok "Removed /setup directory."
    fi

    # Lock the config file
    chmod 0644 "${CONFIG_FILE}"
    chown www-data:www-data "${CONFIG_FILE}"

    # Fix final permissions
    chown -R www-data:www-data "${WEB_ROOT}"
    chmod 755 "${WEB_ROOT}/attachments"

    # Write install flag so we skip install on next restart
    echo "installed=$(date -u +%Y-%m-%dT%H:%M:%SZ)" > "${INSTALL_FLAG}"
    echo "version=1.18.3"                            >> "${INSTALL_FLAG}"
    echo "db_host=${MYSQL_HOST}"                     >> "${INSTALL_FLAG}"
    echo "admin_user=${OST_ADMIN_USER}"              >> "${INSTALL_FLAG}"

    ok "Post-install cleanup done."
}

# ─────────────────────────────────────────────────────────────────
#  6. UPGRADE CHECK (for future version bumps)
# ─────────────────────────────────────────────────────────────────
check_upgrade() {
    log "Checking if DB upgrade is needed..."
    # osTicket's upgrader can be triggered via CLI if needed
    # Placeholder for future use
    ok "No upgrade needed."
}

# ─────────────────────────────────────────────────────────────────
#  7. VERIFY INSTALLATION
# ─────────────────────────────────────────────────────────────────
verify_install() {
    log "Verifying installation..."

    local table_count
    table_count=$(mysql -h"${MYSQL_HOST}" -P"${MYSQL_PORT}" \
        --ssl=0 \
        -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" \
        -s -N -e "SELECT COUNT(*) FROM information_schema.tables
                  WHERE table_schema='${MYSQL_DATABASE}'
                  AND table_name LIKE '${MYSQL_PREFIX}%';" 2>/dev/null || echo "0")

    if [ "${table_count}" -gt 10 ]; then
        ok "Database has ${table_count} osTicket tables — looks good."
    else
        warn "Only ${table_count} tables found. Installation may be incomplete."
    fi
}

# ─────────────────────────────────────────────────────────────────
#  MAIN
# ─────────────────────────────────────────────────────────────────
main() {
    echo ""
    echo -e "${BLUE}╔═══════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║   osTicket v1.18.3 — Docker Startup   ║${NC}"
    echo -e "${BLUE}╚═══════════════════════════════════════╝${NC}"
    echo ""

    # Always wait for DB
    wait_for_mysql

    if [ -f "${INSTALL_FLAG}" ]; then
        # ── Already installed — just start services ───────────────
        ok "osTicket already installed ($(grep installed ${INSTALL_FLAG} | cut -d= -f2))."
        check_upgrade
    else
        # ── First boot — full install ─────────────────────────────
        log "First boot detected — running full automated install..."
        write_config
        run_installer
        post_install_cleanup
        verify_install

        echo ""
        echo -e "${GREEN}╔══════════════════════════════════════════════════╗${NC}"
        echo -e "${GREEN}║            ✓  INSTALLATION COMPLETE              ║${NC}"
        echo -e "${GREEN}╠══════════════════════════════════════════════════╣${NC}"
        echo -e "${GREEN}║  URL:   ${OST_HELPDESK_URL}${NC}"
        echo -e "${GREEN}║  Admin: ${OST_ADMIN_USER} / (password in .env)   ║${NC}"
        echo -e "${GREEN}║  Email: ${OST_ADMIN_EMAIL}${NC}"
        echo -e "${GREEN}╚══════════════════════════════════════════════════╝${NC}"
        echo ""
    fi

    # ── Start cron ─────────────────────────────────────────────────
    log "Starting cron daemon..."
    service cron start
    ok "Cron started."

    # ── Start Apache (foreground — keeps container alive) ──────────
    log "Starting Apache..."
    exec apache2-foreground
}

main "$@"