#!/bin/bash
# ─────────────────────────────────────────────────────────────────
#  osTicket Entrypoint — Zero-touch automated installer
#  Runs on every container start; idempotent (safe to re-run)
# ─────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Colours for readable logs ─────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; NC='\033[0m'

log()  { echo -e "${CYAN}[$(date '+%H:%M:%S')]${NC} $*"; }
ok()   { echo -e "${GREEN}[$(date '+%H:%M:%S')] ✓${NC} $*"; }
warn() { echo -e "${YELLOW}[$(date '+%H:%M:%S')] ⚠${NC} $*"; }
err()  { echo -e "${RED}[$(date '+%H:%M:%S')] ✗${NC} $*"; }

# ── Required env vars (with defaults from compose) ────────────────
MYSQL_HOST="${MYSQL_HOST:-mysql}"
MYSQL_PORT="${MYSQL_PORT:-3306}"
MYSQL_DATABASE="${MYSQL_DATABASE:-osticket}"
MYSQL_USER="${MYSQL_USER:-osticket}"
MYSQL_PASSWORD="${MYSQL_PASSWORD:-0sT1ck3tPass!}"
MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD:-R00tS3cur3Pass!}"
MYSQL_PREFIX="${MYSQL_PREFIX:-ost_}"

OST_ADMIN_EMAIL="${OST_ADMIN_EMAIL:-admin@example.com}"
OST_ADMIN_FNAME="${OST_ADMIN_FNAME:-Admin}"
OST_ADMIN_LNAME="${OST_ADMIN_LNAME:-User}"
OST_ADMIN_USER="${OST_ADMIN_USER:-ostadmin}"
OST_ADMIN_PASS="${OST_ADMIN_PASS:-Adm1nP@ss!}"

OST_SITE_NAME="${OST_SITE_NAME:-Support Center}"
OST_SITE_EMAIL="${OST_SITE_EMAIL:-support@example.com}"
OST_HELPDESK_URL="${OST_HELPDESK_URL:-http://localhost:8080}"

INSTALL_FLAG="/var/www/html/attachments/.installed"
CONFIG_FILE="/var/www/html/include/ost-config.php"
WEB_ROOT="/var/www/html"

# ─────────────────────────────────────────────────────────────────
#  1. WAIT FOR MYSQL
# ─────────────────────────────────────────────────────────────────
wait_for_mysql() {
    log "Waiting for MySQL at ${MYSQL_HOST}:${MYSQL_PORT}..."
    local retries=0
    local max=60

    # Phase 1: wait for TCP port to be open (works regardless of auth)
    until nc -z "${MYSQL_HOST}" "${MYSQL_PORT}" 2>/dev/null; do
        retries=$((retries + 1))
        if [ $retries -ge $max ]; then
            err "MySQL TCP port never opened. Aborting."
            err "DNS check: $(getent hosts ${MYSQL_HOST} 2>&1 || echo 'hostname not resolved')"
            err "Network: $(ip route 2>/dev/null | head -5)"
            exit 1
        fi
        # Every 10 attempts, print a status line
        if [ $((retries % 10)) -eq 0 ]; then
            echo ""
            log "Still waiting... attempt ${retries}/${max}. DNS: $(getent hosts ${MYSQL_HOST} 2>/dev/null || echo 'unresolved')"
        else
            echo -n "."
        fi
        sleep 2
    done
    echo ""
    log "MySQL TCP port is open. Waiting for server to accept queries..."

    # Phase 2: wait for MySQL to actually accept connections
    # Use root for the ping — the osticket user may not exist yet
    retries=0
    until mysqladmin ping \
          -h"${MYSQL_HOST}" \
          -P"${MYSQL_PORT}" \
          -uroot \
          -p"${MYSQL_ROOT_PASSWORD}" \
          --ssl=0 \
          --silent 2>/dev/null; do
        retries=$((retries + 1))
        if [ $retries -ge $max ]; then
            err "MySQL did not become ready in time. Aborting."
            exit 1
        fi
        echo -n "."
        sleep 2
    done
    echo ""
    ok "MySQL is ready."
}

# ─────────────────────────────────────────────────────────────────
#  2. WRITE ost-config.php
# ─────────────────────────────────────────────────────────────────
write_config() {
    log "Writing ost-config.php..."
    chmod 0666 "${CONFIG_FILE}"

    # Build the config — we patch the sample config in-place
    # osTicket's config format uses define() calls
    # Always set OSTINSTALLED to FALSE initially - automated installer will set it to TRUE
    cat > "${CONFIG_FILE}" << PHPCONFIG
<?php
# osTicket Configuration — auto-generated by Docker entrypoint
# DO NOT EDIT MANUALLY

define('OSTINSTALLED',FALSE);
define('SECRET_SALT','$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)');
define('DBDRIVER','mysqli');
define('DBHOST','${MYSQL_HOST}');
define('DBNAME','${MYSQL_DATABASE}');
define('DBUSER','${MYSQL_USER}');
define('DBPASS','${MYSQL_PASSWORD}');
define('DBPREFIX','${MYSQL_PREFIX}');
define('DBPORT','${MYSQL_PORT}');
define('DBSSLCA','');
define('DBSSLCERT','');
define('DBSSLKEY','');
define('DBSSL',false);

define('TABLE_PREFIX','${MYSQL_PREFIX}');

@define('ATTACHMENT_PATH','${WEB_ROOT}/attachments/');
@define('BOOTSTRAP','${WEB_ROOT}/bootstrap.php');
PHPCONFIG

    # Lock config after writing
    chmod 0644 "${CONFIG_FILE}"
    chown www-data:www-data "${CONFIG_FILE}"
    ok "ost-config.php written (OSTINSTALLED=FALSE - will be set by installer)"
}

# ─────────────────────────────────────────────────────────────────
#  3. RUN AUTOMATED INSTALLER
# ─────────────────────────────────────────────────────────────────
run_installer() {
    log "Running automated web-based installer..."
    
    local web_installer="/usr/local/bin/web-install.sh"
    if [ ! -f "${web_installer}" ]; then
        err "Web installer not found: ${web_installer}"
        exit 1
    fi
    
    # Run installation via web interface
    local install_log="/tmp/install-$(date +%s).log"
    bash "${web_installer}" 2>&1 | tee "${install_log}"
    local exit_code=$?
    
    if [ ${exit_code} -eq 0 ]; then
        ok "Automated installation completed"
    else
        err "Automated installation failed (exit code: ${exit_code})"
        warn "Installation log saved to: ${install_log}"
        warn "Last 50 lines of installation log:"
        tail -50 "${install_log}" >&2
        err "Installation will be retried on next restart"
        return 1
    fi
}

# ─────────────────────────────────────────────────────────────────
#  4. POST-INSTALL CLEANUP
# ─────────────────────────────────────────────────────────────────
post_install_cleanup() {
    log "Running post-install cleanup..."

    # Verify installation was successful
    local table_count
    table_count=$(mysql -h"${MYSQL_HOST}" -P"${MYSQL_PORT}" \
        --ssl=0 \
        -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" \
        -s -N -e "SELECT COUNT(*) FROM information_schema.tables
                  WHERE table_schema='${MYSQL_DATABASE}'
                  AND table_name LIKE '${MYSQL_PREFIX}%';" 2>/dev/null || echo "0")

    if [ "${table_count}" -lt 10 ]; then
        err "Installation verification failed: only ${table_count} tables found."
        err "Installation will be retried on next container restart."
        return 1
    fi

    ok "Installation verified: ${table_count} osTicket tables created."

    # Verify config file has OSTINSTALLED=TRUE
    if ! grep -q "define('OSTINSTALLED',TRUE)" "${CONFIG_FILE}"; then
        warn "Config file not marked as installed - installation may have failed"
        return 1
    fi

    ok "Config file marked as installed"

    # DELETE /setup directory IMMEDIATELY for security (critical for idempotency!)
    # This must happen before the install flag is written and Apache starts
    if [ -d "${WEB_ROOT}/setup" ]; then
        log "Removing /setup directory for security (CRITICAL - prevents re-installation)..."
        rm -rf "${WEB_ROOT}/setup"
        ok "/setup directory removed"
    fi

    # Verify /setup is actually gone
    if [ -d "${WEB_ROOT}/setup" ]; then
        err "/setup directory still exists - cannot proceed!"
        return 1
    fi

    # Lock the config file
    chmod 0644 "${CONFIG_FILE}"
    chown www-data:www-data "${CONFIG_FILE}"

    # Fix final permissions
    chown -R www-data:www-data "${WEB_ROOT}"
    chmod 755 "${WEB_ROOT}/attachments"
    # We will only delete /setup on subsequent boots if it somehow remains.

    # Write install flag so we know first boot is done
    echo "installed=$(date -u +%Y-%m-%dT%H:%M:%SZ)" > "${INSTALL_FLAG}"
    echo "version=1.18.3"                            >> "${INSTALL_FLAG}"
    echo "db_host=${MYSQL_HOST}"                     >> "${INSTALL_FLAG}"
    echo "admin_user=${OST_ADMIN_USER}"              >> "${INSTALL_FLAG}"
    echo "status=awaiting_setup_wizard"              >> "${INSTALL_FLAG}"

    ok "Post-install cleanup done. osTicket setup wizard is ready."
}

# ─────────────────────────────────────────────────────────────────
#  5. UPGRADE CHECK (for future version bumps)
# ─────────────────────────────────────────────────────────────────
check_upgrade() {
    log "Checking if DB upgrade is needed..."
    # osTicket's upgrader can be triggered via CLI if needed
    # Placeholder for future use
    ok "No upgrade needed."
}

# ─────────────────────────────────────────────────────────────────
#  6. VERIFY INSTALLATION
# ─────────────────────────────────────────────────────────────────
verify_install() {
    log "Verifying installation..."

    local table_count
    table_count=$(mysql -h"${MYSQL_HOST}" -P"${MYSQL_PORT}" \
        --ssl=0 \
        -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" \
        -s -N -e "SELECT COUNT(*) FROM information_schema.tables
                  WHERE table_schema='${MYSQL_DATABASE}'
                  AND table_name LIKE '${MYSQL_PREFIX}%';" 2>/dev/null || echo "0")

    if [ "${table_count}" -gt 10 ]; then
        ok "Database has ${table_count} osTicket tables — looks good."
    else
        warn "Only ${table_count} tables found. Installation may be incomplete."
    fi
}

# ─────────────────────────────────────────────────────────────────
#  MAIN
# ─────────────────────────────────────────────────────────────────
main() {
    echo ""
    echo -e "${BLUE}╔═══════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║   osTicket v1.18.3 — Docker Startup   ║${NC}"
    echo -e "${BLUE}╚═══════════════════════════════════════╝${NC}"
    echo ""

    # Always wait for DB
    wait_for_mysql || { err "Failed to connect to MySQL"; exit 1; }

    if [ -f "${INSTALL_FLAG}" ]; then
        # ── Already installed — just start services ───────────────
        ok "osTicket already installed ($(grep installed ${INSTALL_FLAG} | cut -d= -f2))."
        
        # Verify config file is properly set
        if ! grep -q "define('OSTINSTALLED',TRUE)" "${CONFIG_FILE}" 2>/dev/null; then
            err "Config file not properly installed - corrupted state detected"
            rm -f "${INSTALL_FLAG}"
            err "Removed install flag - will reinstall on next restart"
            exit 1
        fi
        
        # MUST REMOVE /setup BEFORE APACHE STARTS (prevents setup wizard from running)
        # This is critical for idempotency on every restart
        if [ -d "${WEB_ROOT}/setup" ]; then
            log "Removing /setup directory for security (preventing setup wizard re-trigger)..."
            rm -rf "${WEB_ROOT}/setup"
            ok "/setup directory removed"
        fi
        
        # Verify it's actually gone to prevent accidental re-installation
        if [ -d "${WEB_ROOT}/setup" ]; then
            err "/setup directory could not be removed - this will cause setup wizard to appear"
            err "Manual intervention required: docker exec osticket_app rm -rf /var/www/html/setup"
            exit 1
        fi
        
        # Validate schema signature
        log "Validating schema signature..."
        local sig_file="${WEB_ROOT}/include/upgrader/streams/core.sig"
        if [ -f "${sig_file}" ]; then
            local expected_sig=$(cat "${sig_file}")
            local current_sig=$(mysql -h"${MYSQL_HOST}" -P"${MYSQL_PORT}" --ssl=0 \
                -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" "${MYSQL_DATABASE}" \
                2>/dev/null -N -e "SELECT value FROM ${MYSQL_PREFIX}config WHERE namespace='core' AND \`key\`='schema_signature' LIMIT 1")
            
            if [ "${current_sig}" != "${expected_sig}" ]; then
                warn "Schema signature mismatch! Updating from '${current_sig}' to '${expected_sig}'"
                mysql -h"${MYSQL_HOST}" -P"${MYSQL_PORT}" --ssl=0 \
                    -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" "${MYSQL_DATABASE}" \
                    2>/dev/null <<EOF
UPDATE ${MYSQL_PREFIX}config SET value='${expected_sig}' WHERE namespace='core' AND \`key\`='schema_signature';
EOF
            fi
        fi
        
        check_upgrade
    else
        # Ensure attachment directory exists and is writable
        mkdir -p "${WEB_ROOT}/attachments" || { err "Failed to create attachments directory"; exit 1; }
        chmod 775 "${WEB_ROOT}/attachments" || { err "Failed to chmod attachments directory"; exit 1; }
        
        # ── First boot — full install ─────────────────────────────
        log "First boot detected — running full automated install..."
        write_config || { err "Failed to write config"; exit 1; }
        
        # Start Apache in background for web-based installer
        log "Starting Apache in background for installation..."
        apache2-foreground &
        APACHE_PID=$!
        
        # Wait a moment for Apache to initialize
        sleep 3
        
        # Run the web-based installer
        run_installer || {
            warn "Installation incomplete - will retry on next restart"
            kill $APACHE_PID 2>/dev/null || true
            wait $APACHE_PID 2>/dev/null || true
        }
        
        # Kill background Apache - we'll restart it properly at the end
        log "Stopping background Apache..."
        kill $APACHE_PID 2>/dev/null || true
        wait $APACHE_PID 2>/dev/null || true
        sleep 2
        
        # Perform post-install cleanup and verification
        if post_install_cleanup; then
            verify_install
            
            # Mark as installed
            echo "installed=$(date -u +"%Y-%m-%d %H:%M:%S UTC")" > "${INSTALL_FLAG}"
            chmod 644 "${INSTALL_FLAG}"

            echo ""
            echo -e "${GREEN}╔══════════════════════════════════════════════════╗${NC}"
            echo -e "${GREEN}║   ✓  osTicket Installation Complete             ║${NC}"
            echo -e "${GREEN}╠══════════════════════════════════════════════════╣${NC}"
            echo -e "${GREEN}║  System is fully functional and ready!           ║${NC}"
            echo -e "${GREEN}║                                                  ║${NC}"
            echo -e "${GREEN}║  Access your helpdesk:                           ║${NC}"
            echo -e "${GREEN}║  ${OST_HELPDESK_URL}                              ║${NC}"
            echo -e "${GREEN}║                                                  ║${NC}"
            echo -e "${GREEN}║  Admin panel:                                    ║${NC}"
            echo -e "${GREEN}║  ${OST_HELPDESK_URL}/scp/                         ║${NC}"
            echo -e "${GREEN}║  Username: ${OST_ADMIN_USER}                      ║${NC}"
            echo -e "${GREEN}║  Password: (from OST_ADMIN_PASS env)             ║${NC}"
            echo -e "${GREEN}╚══════════════════════════════════════════════════╝${NC}"
            echo ""
        else
            warn "Installation verification failed - continuing anyway..."
            warn "System may not be fully functional"
        fi
    fi

    # ── Start cron ─────────────────────────────────────────────────
    log "Starting cron daemon..."
    service cron start || warn "Failed to start cron"
    ok "Cron started."

    # ── Start Apache (foreground — keeps container alive) ──────────
    log "Starting Apache..."
    exec apache2-foreground
}

main "$@"